version: '3'
services:
    gitbook:

        container_name: gitbook
        image: gitbook

        working_dir: /app/src

        environment:
            - HTTP_PROXY
            - HTTPS_PROXY
            - GITHUB_URL
            - BUILD_EACH_NBMINUTES
            - DEBUG

        ports:
            - "8080:80"
