version: '3'
services:
    ezmaster-gitbook:

        container_name: ezmaster-gitbook
        build:
            context: .
            args:
                - http_proxy
                - https_proxy

        image: ezmaster-gitbook:1.1.5

        working_dir: /app/src

        environment:
            - HTTP_PROXY
            - HTTPS_PROXY
            - GITHUB_URL_MARKDOWN
            - GITHUB_URL_CONFIG
            - BUILD_EACH_NBMINUTES
            - GITBOOK_DEBUG=1
            - USERID
            - GROUPID

        ports:
            - "8080:80"

        volumes:
            - .:/app
