version: '3'
services:
    ezmaster-gitbook:

        container_name: ezmaster-gitbook
        image: ezmaster-gitbook:1.0.0

        working_dir: /app/src

        environment:
            - HTTP_PROXY
            - HTTPS_PROXY
            - GITHUB_URL
            - BUILD_EACH_NBMINUTES
            - GITBOOK_DEBUG=0

        ports:
            - "8080:80"
