version: '3'
services:
    ezmaster-gitbook:

        container_name: ezmaster-gitbook
        image: ezmaster-gitbook:1.1.3

        working_dir: /app/src

        environment:
            - HTTP_PROXY
            - HTTPS_PROXY
            - GITHUB_URL_MARKDOWN
            - GITHUB_URL_CONFIG
            - BUILD_EACH_NBMINUTES

        ports:
            - "8080:80"
