version: '3'
services:
    ezmaster-gitbook:

        container_name: ezmaster-gitbook
        build:
            context: .
            args:
                - http_proxy
                - https_proxy

        image: ezmaster-gitbook:1.0.0

        working_dir: /app/src

        environment:
            - HTTP_PROXY
            - HTTPS_PROXY
            - GITHUB_URL
            - BUILD_EACH_NBMINUTES
            - DEBUG

        ports:
            - "8080:80"

        volumes:
            - .:/app

        command: bash -c "npm run watch"
